# Multi-Agent Quality Enforcement Configuration
# Implements BMAD standardization with architectural enforcement

# Core System Configuration
bmad_integration:
  version: "1.0"
  enforcement_mode: "mandatory"
  quality_first_principle: true

# Document Access Control (Leverages Claude Code directory restrictions)
document_access:
  agents_can_read:
    - "docs/sharded/**/*.md"
    - "docs/templates/**/*.md" 
    - "docs/standards/**/*.md"
    - "docs/stories/**/*.md"
    - ".claude/config/**/*.yaml"
  
  agents_cannot_read:
    - "docs/archive/**/*"          # Full documents hidden from agents
    - "docs/draft/**/*"            # Incomplete work not accessible
    - "docs/admin/**/*"            # System files protected
    - ".bmad-core/**/*"            # BMAD source files protected

# Quality Gate Configuration (Implemented via Hooks)
quality_gates:
  template_compliance:
    enabled: true
    enforcement: "mandatory"
    validation_hook: "validate_template_compliance.sh"
    block_on_failure: true
  
  dod_completion:
    enabled: true
    enforcement: "mandatory"
    validation_hook: "validate_dod_completion.sh"
    evidence_required: true
    verification_agent_required: true
  
  evidence_collection:
    enabled: true
    enforcement: "mandatory"
    required_evidence:
      - "test_logs"
      - "build_output"
      - "functionality_demo"
    validation_hook: "validate_evidence.sh"
  
  workflow_state:
    enabled: true
    enforcement: "mandatory"
    state_validation_hook: "validate_workflow_state.sh"
    handoff_artifacts_required: true

# Template System Configuration
templates:
  storage_method: "embedded_in_claude_md"
  template_location: "docs/templates/"
  variable_substitution: true
  compliance_validation: "mandatory"
  
  available_templates:
    - name: "story_template"
      file: "story-template.md"
      required_sections: ["status", "story", "acceptance_criteria", "tasks", "dev_notes", "evidence"]
    - name: "prd_template" 
      file: "prd-template.md"
      required_sections: ["goals", "requirements", "epics", "stories"]
    - name: "review_template"
      file: "review-template.md"
      required_sections: ["code_quality", "functionality", "performance", "security"]

# Agent Coordination (External orchestration required due to Claude Code limitations)
agent_coordination:
  method: "file_based_state_management"
  state_persistence_path: "docs/workflow_state/"
  handoff_artifacts_path: "docs/handoffs/"
  status_tracking_enabled: true
  
  coordination_rules:
    - "agents_must_load_previous_state"
    - "agents_must_update_status_on_completion"
    - "agents_must_provide_handoff_artifacts"
    - "quality_gates_block_status_transitions"

# Logging and Metrics (Leverages built-in OpenTelemetry)
monitoring:
  opentelemetry_enabled: true
  quality_metrics_collection: true
  session_tracking: true
  
  custom_metrics:
    - "template_compliance_rate"
    - "dod_completion_rate"
    - "evidence_quality_score"
    - "workflow_efficiency"
    - "rework_frequency"
  
  logging_paths:
    quality_logs: "logs/quality/"
    session_logs: "logs/sessions/"
    error_logs: "logs/errors/"

# Continuous Improvement Configuration
learning_system:
  enabled: true
  data_collection: "automatic"
  pattern_analysis: "weekly"
  improvement_deployment: "controlled_rollout"
  
  learning_metrics:
    - "failure_patterns"
    - "success_patterns" 
    - "efficiency_trends"
    - "quality_improvements"
  
  improvement_frequency:
    template_refinements: "weekly"
    workflow_optimizations: "bi_weekly"
    standard_enhancements: "monthly"
    architecture_evolution: "quarterly"

# Security and Compliance
security:
  container_isolation: false  # Not available in Claude Code
  directory_restrictions: true  # Built-in Claude Code feature
  permission_enforcement: true
  audit_trail: true
  
  compliance_standards:
    - "template_compliance_required"
    - "evidence_collection_mandatory"
    - "quality_gates_non_bypassable"
    - "state_management_required"

# Tool Permission Configuration (Leverages Claude Code tool permissions)
tool_permissions:
  pre_tool_use_validation: true
  quality_gate_hooks_enabled: true
  
  restricted_tools:
    - name: "Write"
      condition: "template_compliance_validated"
    - name: "Edit"
      condition: "quality_gates_passed"
    - name: "MultiEdit"
      condition: "evidence_collected"

# Agent Behavior Configuration
agent_behavior:
  mandatory_config_loading: true
  template_compliance_required: true
  quality_gates_blocking: true
  evidence_provision_mandatory: true
  
  failure_handling:
    template_violation: "stop_execution"
    quality_gate_failure: "block_progression"
    evidence_missing: "require_completion"
    workflow_state_invalid: "rollback_state"