# Development overrides for docker-compose.yml
services:
  qvf-api:
    build:
      target: builder  # Use builder stage for hot reload
    environment:
      - DEBUG=true
      - SECRET_KEY=dev-secret-key-not-for-production
      - LOG_LEVEL=DEBUG
    volumes:
      - ./apps/api/src:/app/src:ro  # Mount source for hot reload
    command: ["uvicorn", "qvf_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--workers", "1"]
    ports:
      - "8000:8000"
      - "8001:8001"  # Debug port

  qvf-web:
    build:
      target: builder  # Use builder stage for development
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - QVF_API_URL=http://qvf-api:8000
    volumes:
      - ./apps/web/src:/app/src:ro  # Mount source for hot reload
      - ./apps/web/public:/app/public:ro
      - ./apps/web/package.json:/app/package.json:ro
    command: ["pnpm", "dev"]
    ports:
      - "3006:3006"

  redis:
    command: redis-server --appendonly yes  # No password in dev
    environment:
      - REDIS_PASSWORD=

  # Remove nginx for development
profiles:
  - never  # This profile is never activated, effectively removing nginx in dev